# Generated by Django 5.2.7 on 2025-10-30 10:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkoutPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('goal', models.CharField(choices=[('cut', 'Cut (Lose Fat)'), ('bulk', 'Bulk (Gain Muscle)'), ('maintain', 'Maintain Weight')], max_length=20)),
                ('duration_weeks', models.PositiveIntegerField(default=4)),
                ('notes', models.TextField(blank=True, null=True)),
                ('plan_type', models.CharField(choices=[('default', 'Default Plan'), ('custom', 'Custom Plan')], default='custom', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workout_plans', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
