# Generated by Django 5.2.7 on 2025-10-30 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_remove_workoutplan_plan_type_remove_workoutplan_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workoutplan',
            name='goal',
            field=models.CharField(choices=[('cut', 'Cut (Lose Fat)'), ('bulk', 'Bulk (Gain Muscle)'), ('maintain', 'Maintain Weight'), ('home', 'Home Workout (No Equipment)')], max_length=20),
        ),
    ]
