# Generated by Django 5.2.7 on 2025-11-01 13:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_rename_goal_workoutplan_goal_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='selected_workout_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_profiles', to='main_app.workoutplan'),
        ),
    ]
