# Generated by Django 5.2.7 on 2025-11-08 14:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_userprofile_selected_workout_plan'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIAssistant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('response', models.TextField()),
                ('plan_type', models.CharField(blank=True, help_text='Type of plan: workout, meal, or general', max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_conversations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MealPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('goal_type', models.CharField(choices=[('cut', 'Cut (Lose Fat)'), ('bulk', 'Bulk (Gain Muscle)'), ('maintain', 'Maintain Weight'), ('home', 'Home Workout (No Equipment)')], max_length=20)),
                ('daily_calories', models.PositiveIntegerField(help_text='Daily calorie target')),
                ('protein_grams', models.PositiveIntegerField(help_text='Daily protein target in grams')),
                ('carbs_grams', models.PositiveIntegerField(help_text='Daily carbs target in grams')),
                ('fats_grams', models.PositiveIntegerField(help_text='Daily fats target in grams')),
                ('breakfast', models.TextField(help_text='Breakfast meal plan')),
                ('lunch', models.TextField(help_text='Lunch meal plan')),
                ('dinner', models.TextField(help_text='Dinner meal plan')),
                ('snacks', models.TextField(blank=True, help_text='Snacks recommendations', null=True)),
                ('notes', models.TextField(blank=True, help_text='Additional notes and tips', null=True)),
                ('duration_weeks', models.PositiveIntegerField(default=4, help_text='Plan duration in weeks')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meal_plans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('follower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='following', to=settings.AUTH_USER_MODEL)),
                ('following', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('follower', 'following')},
            },
        ),
    ]
