# Generated by Django 5.2.7 on 2025-11-17 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_aiassistant_mealplan_follow'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mealplan',
            name='user',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='show_age_public',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='show_height_public',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='height',
            field=models.IntegerField(blank=True, help_text='Height in cm', null=True),
        ),
        migrations.DeleteModel(
            name='AIAssistant',
        ),
        migrations.DeleteModel(
            name='MealPlan',
        ),
    ]
