# Generated by Django 5.2.7 on 2025-11-17 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_remove_mealplan_user_userprofile_age_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='show_fitness_info_public',
            field=models.BooleanField(default=False),
        ),
    ]
